apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ipaclusters.freeipa.coglative.com
spec:
  group: freeipa.coglative.com
  names:
    kind: IpaCluster
    plural: ipaclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            dnsForwarders:
              description: A string list of DNS forwarders for name resolution, defaults
                to no forwarders
              items:
                type: string
              type: array
            domainName:
              description: The directory service root name as in "example.com", required
              type: string
            realmName:
              description: The Kerberos realm name as in "EXAMPLE.COM", required
              type: string
            servers:
              description: The instantiation parameters for the nodes
              items:
                properties:
                  address:
                    description: The LB address of a node
                    type: string
                  caEnable:
                    description: Whether to create a CA server / replica on this node,
                      defaults to `false`
                    type: boolean
                  capacity:
                    description: Size of the storage allocation
                    type: object
                  dnsEnable:
                    description: Whether to create a DNS server / replica on this
                      node, defaults to `false`
                    type: boolean
                  externalTrafficPolicy:
                    description: The externalTrafficPolicy of the LoadBalancer Service
                    type: string
                  ntpEnable:
                    description: Whether to create a NTP server / replica on this
                      node, defaults to `false`
                    type: boolean
                  secretName:
                    description: The name of the secret for a node type, defaults
                      to "ipa-server-secrets"
                    type: string
                  serverName:
                    description: The FQDN of the server
                    type: string
                  storageClassName:
                    description: Name of the storage class to use. Will try default
                      storage class if omitted
                    type: string
                required:
                - serverName
                type: object
              type: array
            uidStart:
              description: An integer for the start of the UID numbering range, immutable
                after cluster instantiation, default is defined by FreeIPA
              format: int64
              type: integer
          required:
          - realmName
          - domainName
          - servers
          type: object
        status:
          properties:
            pvQuantity:
              description: Quantity of persistent volumes that are currently generated
              format: int64
              type: integer
            status:
              description: Human-readable status of the controller
              type: string
          required:
          - status
          - pvQuantity
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
