apiVersion: freeipa.coglative.com/v1alpha1
kind: IpaCluster
metadata:
  name: ipacluster-sample
spec:
  realmName: EXAMPLE.COM
  domainName: example.com
  servers:
    - serverName: server1.example.com
      lbAddress: 192.168.0.10
    - serverName: server2.example.com
      lbAddress: 192.168.0.11
