apiVersion: freeipa.coglative.com/v1alpha1
kind: IpaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ipacluster-sample
spec:
  realmName: EXAMPLE.COM
  domainName: example.com
  servers:
    - serverName: server1.example.com
      address: 192.168.0.10
    - serverName: server2.example.com
      address: 192.168.0.11