apiVersion: freeipa.coglative.com/v1alpha1
kind: IpaCluster
metadata:
  name: ipacluster-sample
spec:
  realmName: EXAMPLE.COM
  domainName: example.com
  servers:
    - serverName: server1.example.com
      address: 192.168.0.10
      storageClassName: local-storage
      capacity: 10Gi
    - serverName: server2.example.com
      address: 192.168.0.11
      storageClassName: local-storage
      capacity: 10Gi
